import "@/styles/globals.css";

//import GeistSans from "geist/font/sans";
import { Raleway } from "next/font/google";
import { type Metadata } from "next";

import { StrictMode } from "react";
import { TRPCReactProvider } from "@/trpc/react";

const raleway = Raleway({ subsets: ["latin", "cyrillic", "vietnamese"] })

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${raleway.className}`}>
      <body>
        <StrictMode>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </StrictMode>
      </body>
    </html>
  );
}
